import os
import json
import sys
import argparse
from pathlib import Path
from utils import safe_create_directory, safe_write_file, resolve_path

def generate_skill_structure(
    skill_name: str,
    category: str,
    output_dir: str,
    options: dict
) -> dict:
    """
    スキルパッケージのディレクトリ構造を自動生成する。
    
    @param skill_name: スキル名（kebab-case）
    @param category: カテゴリ ("data_analysis" | "system_automation" | "frontend_ui" | "backend_api" | "document_generation")
    @param output_dir: 出力先ルートディレクトリ
    @param options: オプション
        {
            "include_tests": bool,
            "include_env_example": bool,
            "official_template": str|None,
            "use_react": bool,
            "use_tailwind": bool,
            "slidekit_mode": bool,
            "chrome_extension": bool,
            "wasm_mode": bool
        }
    @return: 生成結果
    """
    root_path = resolve_path(output_dir)
    
    # 1. ルート作成
    safe_create_directory(root_path)
    
    # 2. 共通ディレクトリ
    dirs_to_create = ["scripts", "references", "tests"]
    if category == "frontend_ui":
        dirs_to_create.append("assets")
        if options.get("chrome_extension"):
            dirs_to_create.extend(["icons", "assets/js"])
            if options.get("wasm_mode"):
                dirs_to_create.extend(["wasm/src", "wasm/pkg"])
                
    elif category == "document_generation":
        dirs_to_create.append("templates")
        
    for d in dirs_to_create:
        safe_create_directory(root_path / d)
        
    files_created = []
    
    # 3. 共通ファイル
    readme_content = f"# {skill_name}\n\nGenerated by Skill-Creator-Pro-MAX."
    safe_write_file(root_path / "README.md", readme_content)
    files_created.append("README.md")
    
    license_content = "\"THE SUSHI-WARE LICENSE\"\n<because@sushi.ware> wrote this. As long as you retain this notice you can do whatever you want with this stuff. If we meet some day, and you think this stuff is worth it, you can buy me a sushi 🍣 in return."
    safe_write_file(root_path / "LICENSE", license_content)
    files_created.append("LICENSE")
    
    if options.get("include_env_example", True):
        safe_write_file(root_path / ".env.example", f"# {skill_name} Environment Variables\n# API_KEY=your_key_here\n")
        files_created.append(".env.example")
        
    gitignore_content = ".env\n__pycache__/\nnode_modules/\ntarget/\nwasm/pkg/\n"
    safe_write_file(root_path / ".gitignore", gitignore_content)
    files_created.append(".gitignore")
    
    # 4. カテゴリ固有ファイル
    if category in ["data_analysis", "system_automation"]:
        if options.get("use_python_for_automation", True) or category == "data_analysis":
            safe_write_file(root_path / "scripts" / "main.py", "# main python script\n")
            files_created.append("scripts/main.py")
            safe_write_file(root_path / "requirements.txt", "# requirements\n")
            files_created.append("requirements.txt")
        else:
            safe_write_file(root_path / "scripts" / "main.sh", "#!/bin/bash\n# main bash script\n")
            files_created.append("scripts/main.sh")
            
    elif category == "frontend_ui":
        if options.get("use_react", False):
            safe_write_file(root_path / "package.json", json.dumps({"name": skill_name}, indent=2) + "\n")
            files_created.append("package.json")
            
        if options.get("chrome_extension"):
            manifest = json.dumps({
                "manifest_version": 3,
                "name": skill_name,
                "version": "1.0.0",
                "action": {"default_popup": "popup.html"},
                "background": {"service_worker": "background.js"}
            }, indent=2)
            safe_write_file(root_path / "manifest.json", manifest + "\n")
            files_created.append("manifest.json")
            safe_write_file(root_path / "background.js", "// service worker\n")
            files_created.append("background.js")
            safe_write_file(root_path / "popup.html", "<!DOCTYPE html><html><body><h1>Popup</h1><script src='popup.js'></script></body></html>\n")
            files_created.append("popup.html")
            safe_write_file(root_path / "popup.js", "// popup logic\n")
            files_created.append("popup.js")
            
            if options.get("wasm_mode"):
                cargo_toml = f'[package]\nname = "{skill_name}-wasm"\nversion = "0.1.0"\nedition = "2021"\n[lib]\ncrate-type = ["cdylib", "rlib"]\n[dependencies]\nwasm-bindgen = "0.2"\n'
                safe_write_file(root_path / "wasm" / "Cargo.toml", cargo_toml)
                files_created.append("wasm/Cargo.toml")
                lib_rs = 'use wasm_bindgen::prelude::*;\n\n#[wasm_bindgen]\npub fn process(input: &str) -> String {\n    input.to_string()\n}\n'
                safe_write_file(root_path / "wasm" / "src" / "lib.rs", lib_rs)
                files_created.append("wasm/src/lib.rs")
        else:
            safe_write_file(root_path / "assets" / "index.html", "<!DOCTYPE html><html><body><h1>Hello World</h1></body></html>\n")
            files_created.append("assets/index.html")
            
    elif category == "backend_api":
        safe_write_file(root_path / "package.json", json.dumps({"name": skill_name, "main": "server.js"}, indent=2) + "\n")
        safe_write_file(root_path / "server.js", "// API Server\n")
        files_created.extend(["package.json", "server.js"])

    return {
        "root_dir": str(root_path),
        "files_created": files_created,
        "directories_created": dirs_to_create
    }

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Skill-Creator-Pro-MAX Structure Generator Test")
    parser.add_argument("--test", action="store_true", help="Run tests")
    args = parser.parse_args()

    if args.test:
        test_dir = resolve_path("test_structure")
        if test_dir.exists():
            import shutil
            shutil.rmtree(test_dir)
            
        generate_skill_structure("test-skill-wasm", "frontend_ui", str(test_dir), {"chrome_extension": True, "wasm_mode": True})
        
        # Verify
        assert (test_dir / "manifest.json").exists()
        assert (test_dir / "wasm" / "Cargo.toml").exists()
        assert (test_dir / "wasm" / "src" / "lib.rs").exists()
        assert (test_dir / "scripts").exists()
        
        print(f"Structure generator tests passed. (Generated in {test_dir})")
        
        import shutil
        shutil.rmtree(test_dir)
        sys.exit(0)
